management:

  server:
    port: 19001
  endpoint:
    env:
      enabled: true
      show-values: always
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    java:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
      mode: full
    build:
      enabled: true
    os:
      enabled: true

server:
  port: 19000


info:
  app:
    name: vavr sample
    version: 0.0.1.final
    website: https://blog.csdn.net/qwfys

spring:
  jackson:
    serialization:
      indent-output: true
#      fail-on-empty-beans: false
#    default-property-inclusion: non_empty
